### PR TITLE
feat(schemes:jwt): add custom jwt payload functionality

### LINKED ISSUE #13: Feature Request: Ability to serialize object into JWT Token Payload
_I wanted to start this conversation here before offering a pull request. I want to see what the community thinks as well as project maintainers._

When using Adonis Auth with JWT, the sample code below only serializes the Entities Primary Key into the Payload.

```
const user = yield User.find(1)
const token = yield request.auth.generate(user)
```

Code: https://github.com/adonisjs/adonis-auth/blob/master/src/Schemes/Jwt/index.js#L93-L103

JWT Spec and the `jsonwebtoken` library support providing `object literals` into the payload. It would be very useful if Adonis Auth also supported this use-case. An example of practical use of this feature would be such as if you want to add the Users Profile object into the payload, so you don't need to make another API call for that information (or and it to the response itself).

Without this feature you have to work around it by adding the object into the response body (to avoid another Web I/O).

```
const profile = yield user.profile().fetch();
const token = yield request.auth.generate(user);
response.send({ token: token, profile: profile });
```

Many client side frameworks have built in support for JWT payloads, example Aurelia Auth, which has an API to get the JWT payload. If the payload had an object expected you wouldn't need to do any further processing to get the details of the Users Identity, or any special logic to store and maintain that information through the life of the session, which is something the framework is already doing with the payload.

_Offering this feature is trivial, there are a few different ways I see how it could be done, but first would like to here others thoughts. If anyone wants to see sample change-sets in how this could be achieved I would be glad to provide and discuss further_

### PR DESCRIPTION
**Pull request by starr0stealer**
Add the ability to provide a custom object model to be serialized into the JWT payload

Closes #13

### CODE REVIEW

**Comment by thetutlage** [comment]
Closing since tests are still failing.

**Comment by starr0stealer** [comment]
Test weren't failing, there is some to cover but not from my additions. I was waiting feedback that was requested

**Comment by thetutlage** [comment]
Sorry, my bad

**Comment by thetutlage** [comment]
Can u please rebase the branch and lemme play with it. I am sure that JWT may need more flexibility and lemme see how far and gracefully we can allow that.

**Comment by starr0stealer** [comment]
I will get my branch sync'd up.

**Comment by starr0stealer** [comment]
@thetutlage Everything should be sync'd and passing now

**Comment by thetutlage** [comment]
Yeah looks good!

**Comment by starr0stealer** [comment]
In #13 I have sample usage of this new feature, my second to last comment

**Comment by thetutlage** [comment]
Yes this one looks great to me. I am also concerned if you want to verify something inside the custom payload. Like I add the user `ip-address` to the payload and want to make sure that it is decoded it is checked against the current `ip-address`.

**Comment by starr0stealer** [comment]
Checking of the IP stored in the Payload sounds like custom business logic, something this library shouldn't be concerned with

**Comment by starr0stealer** [comment]
@thetutlage I have resync'd this PR again with develop

**Comment by starr0stealer** [comment]
This will have breaking changes for anyone that was using `identityId ` which is now `uid`. Also worth noting in the Auth0 spec `uid` key in JWT payload is usually the email

**Comment by thetutlage** [comment]
There is no one using `identityId` so far and `uid` needs to be unique identifier which seems to be safe with email but id makes more sense to adonis

**Comment by marines** [comment]
It's not JWT compliant.

**Comment by starr0stealer** [comment]
@marines How so? The `payload` is passed directly to `jsonwebtoken`, there is no explicit definition of the format of the `payload` as its meant to be flexible. This change was the make the JWT feature more compliant by offering the payload feature. It does not add any violations

**Comment by marines** [comment]
Even Adonis' token validation takes `exp` field of the payload which cannot be set manually in this approach. JWT RFC describes recommendations (which are implemented in majority if tools) with which it's not compliant at all. One of the main assumptions of JWT is to make it as short as possible. Why introducing `payload` subkey when it's a payload already?

**Pull request closed without merging**
