### PR TITLE
Api plain attribute

### PR DESCRIPTION
**Pull request by kevmt**
Issue #77

### CODE REVIEW

**Comment by thetutlage** [comment]
May I know what's the issue in Encrypting the token before saving it?

**Comment by kevmt** [comment]
Hi @thetutlage base on the issue.. this is a plain token attribute/flag.

**Comment by thetutlage** [comment]
Yeah but why should Adonis allow plain token?

**Comment by kevmt** [comment]
@thetutlage I don't know, its a matter choice maybe, a requirement for somebody, might be? I know I do require something like it, and I made it as a attribute/config type, and defaults to `false`. I wish I know more about the framework, maybe something we can extend scheme or register our own scheme? Cant find on docs, probably only middleware way.

**Comment by thetutlage** [comment]
As I said, keeping the tokens plain is outside the scope of the library. They will always be saved encrypted. The PR should be to increase the `token` column length to store big values. 

Closing this PR in favor of that

**Pull request closed without merging**
